In [2]:
!pip3 install torch
import torch
import torch.nn as nn #we will use inheritance such that LR will leverage base class nn.Module

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [26]:
#classes are used as templates/construction for creating new objects
#Base class from nn.Module for all NNs, usually #LR class is sub class
#Use double underscores for function here - initialize new instances of class, object that will be initliaized, first argument is self - instance of class
#super() allows more freedom from multiple inheritance from parent classes
#Declare self.lienar represents object we intend to initialize
class LR(nn.Module): 
  def __init__(self, input_size, output_size):
     super().__init__() 
     self.linear=nn.Linear(input_size, output_size) 
  def forward(self, x):
    pred = self.linear(x)
    return pred


In [27]:
torch.manual_seed(1)
model = LR(1,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [28]:
x = torch.tensor([1.0])
model = LR(1,1)
print(model.forward(x))

tensor([0.2755], grad_fn=<AddBackward0>)
